# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import emil.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laughs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_id', models.CharField(default=emil.models.gen_rand_str, max_length=10, unique=True)),
                ('smileage', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='laughs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emil.User'),
        ),
    ]
