# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emil', '0002_auto_20171028_0735'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Laughs',
            new_name='Laugh',
        ),
    ]
