# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 19:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emil', '0004_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laugh',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
