# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'emil' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for emil
  pod 'SwiftyJSON'

  target 'emilTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'emilUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
